config/routes.rb
Rails.application.routes.draw do
  get 'errors/new'

  get 'product_pictures/new'

  get 'products/new'

  get 'categories/new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :categories do 
    collection do
      put 'activate'
    end
  end

  resources :products do
    collection do
      put 'activate'
    end
  end

  resources :users do
    collection do
      put 'activate'
    end

    member do
      delete 'delete_image' => 'users#destroy', as: :delete_image
    end
  end
  
  resources :product_pictures do
    member do
      delete 'delete_picture' => 'product_pictures#destroy', as: :delete_picture
    end
  end
  match '*a', :to => 'errors#routing', via: :get
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	validates :name, presence: true, length: {maximum: 50},
					format: { with: /\A[a-zA-Z0-9_.]*\Z/i, :message => "can not have special character" }
	validates :email, presence: true, length: {maximum: 255},
					format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, 
							:message => "can not have special character", allow_blank: true },
					uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: {minimum: 6}, allow_blank: true
	mount_uploader :picture, PictureUploader

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def self.search(search)
		if "activated".include?("#{search}")
			active = true
		end
		if "deactived".include?("#{search}")
		 	deactive = false	
		end
		where('name LIKE ? OR id LIKE ? OR active LIKE ? OR active LIKE ?', "%#{search}%", "%#{search}%", active, deactive)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def initialize
    super
    @model = User
    @model_ids = :user_ids
    @model_symb = :user
    @model_method = :users_path
    @model_params = { key1: :name, key2: :email, key3: :password, 
                      key4: :password_confirmation, key5: :picture, key6: :active }
  end

  def destroy
    image = User.find(params[:id]).picture
    image.remove!
    redirect_to :back
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture, :active)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body>
	<div class="content">


    <div class="breadLine">

        <ul class="breadcrumb">
            <li><a href="<%= users_path %>">List Users</a> <span class="divider">></span></li>
            <li class="active">Edit</li>
        </ul>

    </div>

    	<div class="workplace">

        	<div class="row-fluid">

            	<div class="span12">
                	<div class="head">
                    	<div class="isw-grid"></div>
                    	<h1>Users Management</h1>

                    	<div class="clear"></div>
                	</div>
                	<div class="block-fluid">
                    	
                    		<%= form_for(@model_obj, html: {multipart: true}) do |f| %>
                    		<%#= render 'shared/error_messages' %>
                    		<div class="row-form">
                            	<div class="span3">Username:</div>
                            	<div class="span9"> <%= f.text_field :name, :placeholder => "some text value..." %> 
                                <% f.object.errors[:name].each do |msg| %>
                                    <li style="color: red">
                                        <%= msg%>
                                    </li>
                                <% end %>
                                </div>
                            	<div class="clear"></div>
                            </div> 
                    		<div class="row-form">
                            	<div class="span3">Email:</div>
                            	<div class="span9"> <%= f.text_field :email, :placeholder => "some text value..." %> 
                                <% f.object.errors[:email].each do |msg| %>
                                    <li style="color: red">
                                        <%= msg%>
                                    </li>
                                <% end %>
                                </div>
                            	<div class="clear"></div>
                        	</div> 
                    		<div class="row-form">
                            	<div class="span3">Password:</div>
                            	<div class="span9"> <%= f.password_field :password, :placeholder => "some text value..." %> 
                                <% f.object.errors[:password].each do |msg| %>
                                    <li style="color: red">
                                        <%= msg%>
                                    </li>
                                <% end %>
                                </div>
                            	<div class="clear"></div>
                        	</div> 
                    		<div class="row-form">
                            	<div class="span3">Upload Avatar:</div>
                            	<div class="span9">
                                <p>
                                    <%= image_tag @model_obj.picture_url, size: "50x50" if @model_obj.picture? %>
                                </p>
                            	<%= f.file_field :picture %>
                                <% if @model_obj.picture? %>
                                <p> 
                                    <%= link_to "Delete image", delete_image_user_path, method: :delete, data: {confirm: "Are you sure?"} %> 	
                                </p>
                                <% end %>
                            	</div>
                            	<div class="clear"></div>
                        	</div> 
                        	<div class="row-form">
                            	<div class="span3">Activate:</div>
                            	<div class="span9">
                                	<%= f.select :active, [["Active", true], ["Deactive", false]] %>
                            	</div>
                            	<div class="clear"></div>
                        	</div>                          
                        	<div class="row-form">
                        		<%= f.submit "Update", class: "btn btn-success" %>
								<div class="clear"></div>
                        	</div>
                        	<% end %>
                    	<div class="clear"></div>
                	</div>
            	</div>
        	</div>
        	<div class="dr"><span></span></div>
    	</div>
	</div>
</body>
	

app/views/users/index.html.erb
<div class="content">
<%#= @a.inspect %>
    <div class="breadLine">

        <ul class="breadcrumb">
            <li><%= link_to "List Users", users_path %></li>
        </ul>

    </div>

    <div class="workplace">

        <div class="row-fluid">
            <div class="span12 search">
                <%= form_tag users_path, :method => 'get' do %>
                    <%= text_field_tag :search, params[:search], :class => "span11", :placeholder => "Some text for search..." %>
                    <button class="btn span1" type="submit">Search</button>
                <% end %>
            </div>
        </div>
        <!-- /row-fluid-->

        <div class="row-fluid">

            <div class="span12">
                <div class="head">
                    <div class="isw-grid"></div>
                    <h1>Users Management</h1>
                    <div class="clear"></div>
                </div>
                <%= form_tag activate_users_path, method: :put do %>                       
                <div class="block-fluid table-sorting"> 
                    <%= link_to "Add User", new_user_path, :class => "btn btn-add" %>                
                    <table cellpadding="0" cellspacing="0" width="100%" class="table" id="tSortable_2">
                        <thead>                    
                        <tr>
                            <th><input type="checkbox" id="checkAll" value="checkAll" /></th>

                            <th width="15%" class="sorting"><%= link_to "ID", search: params[:search],
                                                                    col: :id, :sort => @sort_type %>
                            </th>
                            <th width="35%" class="sorting"><%= link_to "Username", search: params[:search],
                                                                        col: :name, :sort => @sort_type %>
                            </th>
                            <th width="20%" class="sorting"><%= link_to "Activate", search: params[:search],
                                                                      col: :active, :sort => @sort_type %>
                            </th>
                            <th width="10%" class="sorting"><%= link_to "Time Created", search: params[:search],
                                                                        col: :created_at, :sort => @sort_type %>
                            </th>
                            <th width="10%" class="sorting"><%= link_to "Time Updated", search: params[:search],
                                                                        col: :updated_at, :sort => @sort_type %>
                            </th>
                            <th width="10%">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <% @model_objs.each do |object| %>
                        <tr>
                            <td><%= check_box_tag "user_ids[]", object.id %></td>
                            <td><%= object.id %></td>
                            <td><%= object.name %></td>
                            <%if object.active == true %>
                                <td><span class="text-success">Activated</span></td>
                            <%else%>
                                <td><span class="text-error">Deactived</span></td>
                            <%end%>
                            <td><%= object.created_at %></td>
                            <td><%= object.updated_at %></td>
                            <td><%= link_to "Edit", edit_user_path(object), :class => "btn btn-info" %></td>
                        </tr>
                        <% end %>
                        </tbody>
                    </table>
                    <div>
                        <%= submit_tag "Activate", :name => "Activate", :class => "btn btn-success" %>
                        <%= submit_tag "Delete", :name => "Delete", :class => "btn btn-danger" %>
                    </div><!-- /bulk-action-->
                    
                    <div class="dataTables_paginate">
                        <%= will_paginate @model_objs %>
                    </div>
                    <div class="clear"></div>
                       
                </div>
                <% end %> 
            </div>

        </div>
        <div class="dr"><span></span></div>

    </div>

</div>

app/views/users/new.html.erb
<div class="content">


    <div class="breadLine">

        <ul class="breadcrumb">
            <li><a href="<%= users_path %>">List Users</a> <span class="divider">></span></li>
            <li class="active">Add</li>
        </ul>

    </div>

    <div class="workplace">

        <div class="row-fluid">

            <div class="span12">
                <div class="head">
                    <div class="isw-grid"></div>
                    <h1>Users Management</h1>

                    <div class="clear"></div>
                </div>
                <div class="block-fluid">
                    <%= form_for(@model_obj, html: {multipath: true}) do |f| %>
                    <%#= render 'shared/error_messages' %>
                    	<div class="row-form">
                            <div class="span3">Username:</div>
                            <div class="span9"><%= f.text_field :name, :placeholder => "some text value..." %>
                           <% f.object.errors[:name].each do |msg| %>
                                <li style="color: red">
                                <%= msg%>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Email:</div>
                            <div class="span9"><%= f.text_field :email, :placeholder => "some text value..." %>
                            <% f.object.errors[:email].each do |msg| %>
                                <li style="color: red">
                                <%= msg%>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Password:</div>
                            <div class="span9"><%= f.password_field :password, :placeholder => "some text value..."%>
                            <% f.object.errors[:password].each do |msg| %>
                                <li style="color: red">
                                <%= msg%>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Upload Avatar:</div>
                            <div class="span9">
                            <%= f.file_field :picture %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                        <div class="row-form">
                            <div class="span3">Activate:</div>
                            <div class="span9">
                                <%= f.select :active, [["Active", true], ["Deactive", false]]%>
                            </div>
                            <div class="clear"></div>
                        </div>                          
                        <div class="row-form">
                        	<%= f.submit "Create", class: "btn btn-success" %>
							<div class="clear"></div>
                        </div>
                    <% end %>
                    <div class="clear"></div>
                </div>
            </div>

        </div>
        <div class="dr"><span></span></div>

    </div>

</div>