config/routes.rb
Rails.application.routes.draw do
  get 'errors/new'

  get 'product_pictures/new'

  get 'products/new'

  get 'categories/new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :categories do 
    collection do
      put 'activate'
    end
  end

  resources :products do
    collection do
      put 'activate'
    end
  end

  resources :users do
    collection do
      put 'activate'
    end

    member do
      delete 'delete_image' => 'users#destroy', as: :delete_image
    end
  end
  
  resources :product_pictures do
    member do
      delete 'delete_picture' => 'product_pictures#destroy', as: :delete_picture
    end
  end
  match '*a', :to => 'errors#routing', via: :get
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true, length: {maximum: 50},
				format: { with:/\A[a-zA-Z0-9_.]*\Z/i, :message => "can not have special character" },
				uniqueness: { case_sensitive: false }

	def self.search(search)
		if "activated".include?("#{search}")
			active = true
		end
		if "deactived".include?("#{search}")
		 	deactive = false	
		end
		where('name LIKE ? OR id LIKE ? OR active LIKE ? OR active LIKE ?', "%#{search}%", "%#{search}%", active, deactive)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def initialize
    super
    @model = Category
    @model_ids = :category_ids
    @model_symb = :category
    @model_method = :categories_path
    @model_params = { key1: :name, key2: :active }
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="content">


    <div class="breadLine">

        <ul class="breadcrumb">
            <li><%= link_to "List Categories", categories_path %> <span class="divider">></span></li>
            <li class="active">Edit</li>
        </ul>

    </div>

    <div class="workplace">

        <div class="row-fluid">

            <div class="span12">
                <div class="head">
                    <div class="isw-grid"></div>
                    <h1>Categories Management</h1>

                    <div class="clear"></div>
                </div>
                <div class="block-fluid">
                    <%= form_for @model_obj do |f| %>
                    	<div class="row-form">
                            <div class="span3">Category Name:</div>
                            <div class="span9"><%= f.text_field :name, :placeholder => "some text value..."%>
                                <% f.object.errors[:name].each do |msg| %>
                                <li style="color: red">
                                    <%= msg %>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                        <div class="row-form">
                            <div class="span3">Activate:</div>
                            <div class="span9">
                                <%= f.select :active, [["Active", true], ["Deactive", false]] %>
                            </div>
                            <div class="clear"></div>
                        </div>                          
                        <div class="row-form">
                        	<%= f.submit "Update", class: "btn btn-success" %>
							<div class="clear"></div>
                        </div>
                    <% end %>
                    <div class="clear"></div>
                </div>
            </div>

        </div>
        <div class="dr"><span></span></div>

    </div>

</div>

app/views/categories/index.html.erb
<div class="content">
    <div class="breadLine">
        <ul class="breadcrumb">
            <li><%= link_to "List Categories", categories_path %></li>
        </ul>

    </div>

    <div class="workplace">

        <div class="row-fluid">
            <div class="span12 search">
                <%= form_tag categories_path, :method => 'get' do %>
                    <%= text_field_tag :search, params[:search], :class => "span11", :placeholder => "Some text for search..." %>
                    <button class="btn span1" type="submit">Search</button>
                <% end %>
            </div>
        </div>
        <!-- /row-fluid-->

        <div class="row-fluid">

            <div class="span12">
                <div class="head">
                    <div class="isw-grid"></div>
                    <h1>Categories Management</h1>

                    <div class="clear"></div>
                </div>
                <%= form_tag activate_categories_path, method: :put do %> 
                <div class="block-fluid table-sorting">
                    <%= link_to "Add category", new_category_path, :class => "btn btn-add" %>
                    <table cellpadding="0" cellspacing="0" width="100%" class="table" id="tSortable_2">
                        <thead>
                        <tr>
                            <th><input type="checkbox" id="checkAll" value="checkAll" /></th>

                            <th width="15%" class="sorting"><%= link_to "ID", search: params[:search],
                                                                    col: :id, :sort => @sort_type %>
                            </th>
                            <th width="35%" class="sorting"><%= link_to "Username", search: params[:search],
                                                                    col: :name, :sort => @sort_type %>
                            </th>
                            <th width="20%" class="sorting"><%= link_to "Activate", search: params[:search],
                                                                    col: :active, :sort => @sort_type %>
                            </th>
                            <th width="10%" class="sorting"><%= link_to "Time Created", 
                                                                    search: params[:search],
                                                                    col: :created_at, :sort => @sort_type %>
                            </th>
                            <th width="10%" class="sorting"><%= link_to "Time Updated", 
                                                                    search: params[:search],
                                                                    col: :updated_at, :sort => @sort_type %>
                            </th>
                            <th width="10%">Action</th>
                        </tr>
                        </thead>
                        <% @model_objs.each do |object| %>
                        <tbody>
                        <tr>
                            <td><%= check_box_tag "category_ids[]", object.id %></td>
                            <td><%= object.id %></td>
                            <td><%= object.name %></td>
                            <%if object.active == true %>
                                <td><span class="text-success">Activated</span></td>
                            <%else%>
                                <td><span class="text-error">Deactived</span></td>
                            <%end%>
                            <td><%= object.created_at %></td>
                            <td><%= object.updated_at %></td>
                            <td><%= link_to "Edit", edit_category_path(object), :class => "btn btn-info" %>
                            </td>
                        </tr>
                        </tbody>
                        <% end %>
                    </table>
                    <div class="bulk-action">
                        <%= submit_tag "Activate", :name => "Activate", :class => "btn btn-success" %>
                        <%= submit_tag "Delete", :name => "Delete", :class => "btn btn-danger" %>
                    </div><!-- /bulk-action-->
                    <div class="dataTables_paginate">
                        <%#= link_to "First", users_path, :action => :whaterver, :page => 1 %>
                        <%= will_paginate @model_objs %>
                    </div>
                    <div class="clear"></div>
                </div>
                <% end %>
            </div>

        </div>
        <div class="dr"><span></span></div>

    </div>

</div>

app/views/categories/new.html.erb
<div class="content">


    <div class="breadLine">

        <ul class="breadcrumb">
            <li><%= link_to "List Categories", categories_path %> <span class="divider">></span></li>
            <li class="active">Add</li>
        </ul>

    </div>

    <div class="workplace">

        <div class="row-fluid">

            <div class="span12">
                <div class="head">
                    <div class="isw-grid"></div>
                    <h1>Categories Management</h1>

                    <div class="clear"></div>
                </div>
                <div class="block-fluid">
                    <%= form_for @model_obj do |f| %>
                    	<div class="row-form">
                            <div class="span3">Category Name:</div>
                            <div class="span9"><%= f.text_field :name, :placeholder => "some text value..." %>
                            <% f.object.errors[:name].each do |msg| %>
                                <li style="color: red">
                                    <%= msg %>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                        <div class="row-form">
                            <div class="span3">Activate:</div>
                            <div class="span9">
                                <%= f.select :active, [["Active", true], ["Deactive", false]] %>
                            </div>
                            <div class="clear"></div>
                        </div>                          
                        <div class="row-form">
                        	<%= f.submit "Create", class: "btn btn-success" %>
							<div class="clear"></div>
                        </div>
                    <% end %>
                    <div class="clear"></div>
                </div>
            </div>

        </div>
        <div class="dr"><span></span></div>

    </div>

</div>