config/routes.rb
Rails.application.routes.draw do
  get 'errors/new'

  get 'product_pictures/new'

  get 'products/new'

  get 'categories/new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :categories do 
    collection do
      put 'activate'
    end
  end

  resources :products do
    collection do
      put 'activate'
    end
  end

  resources :users do
    collection do
      put 'activate'
    end

    member do
      delete 'delete_image' => 'users#destroy', as: :delete_image
    end
  end
  
  resources :product_pictures do
    member do
      delete 'delete_picture' => 'product_pictures#destroy', as: :delete_picture
    end
  end
  match '*a', :to => 'errors#routing', via: :get
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true, length: {maximum: 50},
			format: { with:/\A[a-zA-Z0-9_.]*\Z/i, :message => "can not have special character" },
			uniqueness: { case_sensitive: false }
	validates :price, presence: true, :numericality => { :greater_than => 0, allow_blank: true }
	has_many :product_pictures
	accepts_nested_attributes_for :product_pictures

	def self.search(search)
		if "activated".include?("#{search}")
			active = true
		end
		if "deactived".include?("#{search}")
		 	deactive = false	
		end
		where('name LIKE ? OR id LIKE ? OR price LIKE? OR active LIKE ? OR active LIKE ?', 
			"%#{search}%", "%#{search}%", "%#{search}%", active, deactive)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def initialize
    super
    @model = Product
    @model_ids = :product_ids
    @model_symb = :product
    @model_method = :products_path
    @model_params = { key1: :name, key2: :price, key3: :description, key4: :active }
    @model_update = :update_product
  end

  def edit
    @product_pictures = @model_obj.product_pictures
  end 

  def create_product_image
    if params[:product_pictures]
      params[:product_pictures]['picture'].each do |i|
          @product_picture = @model_obj.product_pictures.create!(:picture => i, :product_id => @model_obj.id)
      end
    end
  end

  def update_product
    unless params[:product_pictures] == nil 
      params[:product_pictures]['picture'].each do |i|
        @product_picture = @model_obj.product_pictures.create!(:picture => i, :product_id => @model_obj.id)
      end
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="content">


    <div class="breadLine">

        <ul class="breadcrumb">
            <li><%= link_to "List Products", products_path %><span class="divider">></span></li>
            <li class="active">Edit</li>
        </ul>

    </div>

    <div class="workplace">

        <div class="row-fluid">

            <div class="span12">
                <div class="head">
                    <div class="isw-grid"></div>
                    <h1>Products Management</h1>

                    <div class="clear"></div>
                </div>
                <div class="block-fluid">
                    <%= form_for @model_obj do |f| %>
                    	<div class="row-form">
                            <div class="span3">Product Name:</div>
                            <div class="span9"><%= f.text_field :name, :placeholder => "some text value..." %>
                            <% f.object.errors[:name].each do |msg| %>
                                <li style="color: red">
                                    <%= msg %>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Price:</div>
                            <div class="span9"><%= f.text_field :price, :placeholder => "some text value..." %>
                            <% f.object.errors[:price].each do |msg| %>
                                <li style="color: red">
                                    <%= msg %>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Description:</div>
                            <div class="span9"><%= f.text_area :description, :placeholder => "some text value..." %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Upload Image:</div>
                            <div class="span9">
                            <% if @product_pictures %>
                                <% @product_pictures.each do |p| %>
                                    <%= image_tag p.picture_url, :size => "50x50" %>
                                    <%= link_to "Delete", delete_picture_product_picture_path(p.id), method: :delete, data: {confirm: "Are you sure?"} %>
                                <% end %>
                            <%end%>
                            <p><%= f.file_field :picture, :multiple => true, 
                                                    name: "product_pictures[picture][]" %>                  
                            </p>
                            </div>
                            <div class="clear"></div>
                        </div> 
                        <div class="row-form">
                            <div class="span3">Activate:</div>
                            <div class="span9">
                                <%= f.select :active, [["Active", true], ["Deactive", false]] %>
                            </div>
                            <div class="clear"></div>
                        </div>                          
                        <div class="row-form">
                        	<%= f.submit "Update", class: "btn btn-success" %>
							<div class="clear"></div>
                        </div>
                    <% end %>
                    <div class="clear"></div>
                </div>
            </div>

        </div>
        <div class="dr"><span></span></div>

    </div>

</div>

app/views/products/index.html.erb
<div class="content">


    <div class="breadLine">

        <ul class="breadcrumb">
            <li><%= link_to "List Products", products_path %></li>
        </ul>

    </div>

    <div class="workplace">

        <div class="row-fluid">
            <div class="span12 search">
                <%= form_tag products_path, :method => 'get' do %>
                    <%= text_field_tag :search, params[:search], :class => "span11", :placeholder => "Some text for search..." %>
                    <button class="btn span1" type="submit">Search</button>
                <% end %>
            </div>
        </div>
        <!-- /row-fluid-->

        <div class="row-fluid">

            <div class="span12">
                <div class="head">
                    <div class="isw-grid"></div>
                    <h1>Products Management</h1>

                    <div class="clear"></div>
                </div>
                <%= form_tag activate_products_path, method: :put do %>
                <div class="block-fluid table-sorting">
                    <%= link_to "Add Product", new_product_path, :class => "btn btn-add" %>
                    <table cellpadding="0" cellspacing="0" width="100%" class="table" id="tSortable_2">
                        <thead>
                        <tr>
                            <th><input type="checkbox" id="checkAll"/></th>
                            <th width="10%" class="sorting"><%= link_to "ID", search: params[:search],
                                                                    col: :id, :sort => @sort_type %>
                            </th>
                            <th width="30%" class="sorting"><%= link_to "Product Name",
                                                                    search: params[:search],
                                                                    col: :name, :sort => @sort_type %>
                            </th>
                            <th width="15%" class="sorting"><%= link_to "Price", search: params[:search],
                                                                    col: :price, :sort => @sort_type %>
                            </th>
                            <th width="15%" class="sorting"><%= link_to "Activate", search: params[:search],
                                                                    col: :active, :sort => @sort_type %>
                            </th>
                            <th width="10%" class="sorting"><%= link_to "Time Created",
                                                                    search: params[:search],
                                                                    col: :created_at, :sort => @sort_type %>
                            </th>
                            <th width="10%" class="sorting"><%= link_to "Time Updated", 
                                                                    search: params[:search],
                                                                    col: :updated_at, :sort => @sort_type %>
                            </th>
                            <th width="10%">Action</th>
                        </tr>
                        </thead>
                        <% @model_objs.each do |object| %>
                        <tbody>
                        <tr>
                            <td><%= check_box_tag "product_ids[]", object.id %></td>
                            <td><%= object.id %></td>
                            <td><%= object.name %></td>
                            <td><%= object.price %> VND</td>
                            <%if object.active == true %>
                                <td><span class="text-success">Activated</span></td>
                            <%else%>
                                <td><span class="text-error">Deactived</span></td>
                            <%end%>
                            <td><%= object.created_at %></td>
                            <td><%= object.updated_at %></td>
                            <td><%= link_to "Edit", edit_product_path(object), :class => "btn btn-info" %></td>
                        </tr>
                        </tbody>
                        <% end %>
                    </table>
                    <div class="bulk-action">
                        <%= submit_tag "Activate", :name => "Activate", :class => "btn btn-success" %>
                        <%= submit_tag "Delete", :name => "Delete", :class => "btn btn-danger" %>
                    </div><!-- /bulk-action-->
                    <div class="dataTables_paginate">
                        <%= will_paginate @model_objs %>
                    </div>
                    <div class="clear"></div>
                </div>
                <% end %>
            </div>

        </div>
        <div class="dr"><span></span></div>

    </div>

</div>

app/views/products/new.html.erb
<div class="content">


    <div class="breadLine">

        <ul class="breadcrumb">
            <li><%= link_to "List Products", products_path %> <span class="divider">></span></li>
            <li class="active">Add</li>
        </ul>

    </div>

    <div class="workplace">

        <div class="row-fluid">

            <div class="span12">
                <div class="head">
                    <div class="isw-grid"></div>
                    <h1>Products Management</h1>

                    <div class="clear"></div>
                </div>
                <div class="block-fluid">
                    <%= form_for @model_obj do |f| %>
                    	<div class="row-form">
                            <div class="span3">Product Name:</div>
                            <div class="span9"><%= f.text_field :name, :placeholder => "some text value..." %>
                            <% f.object.errors[:name].each do |msg| %>
                                <li style="color: red">
                                    <%= msg%>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Price:</div>
                            <div class="span9"><%= f.text_field :price, :placeholder => "some text value..." %>
                            <% f.object.errors[:price].each do |msg| %>
                                <li style="color: red">
                                    <%= msg%>
                                </li>
                            <% end %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Description:</div>
                            <div class="span9"><%= f.text_area :description, :placeholder => "some text value..." %>
                            </div>
                            <div class="clear"></div>
                        </div> 
                    	<div class="row-form">
                            <div class="span3">Upload Image:</div>
                            <div class="span9">
                            <%= f.fields_for :product_pictures do |p| %>
                            <%= p.file_field :picture, :multiple => true, 
                                                    name: "product_pictures[picture][]", :size => 19 %>
                            </div>
                            <div class="clear"></div>
                            <% end %>
                        </div> 
                        <div class="row-form">
                            <div class="span3">Activate:</div>
                            <div class="span9">
                                <%= f.select :active, [["Active", true], ["Deactive", false]]%>
                            </div>
                            <div class="clear"></div>
                        </div>                          
                        <div class="row-form">
                        	<%= f.submit "Create", class: "btn btn-success" %>
							<div class="clear"></div>
                        </div>
                    <% end %>
                    <div class="clear"></div>
                </div>
            </div>

        </div>
        <div class="dr"><span></span></div>

    </div>

</div>